export const FETCH_COIN = 'FETCH_COIN';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const HANDLE_CURRENCY = 'HANDLE_CURRENCY';
export const UPDATE_DATA_SET = 'UPDATE_DATA_SET';
export const CURRENCY_PRICE = 'CURRENCY_PRICE';
export const UPDATE_COIN = 'UPDATE_COIN';
export const UPDATE_REDDIT_THREAD = 'UPDATE_REDDIT_THREAD';