
export const FETCH_COIN = 'FETCH_COIN';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const HANDLE_CURRENCY = 'HANDLE_CURRENCY';
export const UPDATE_DATA_SET = 'UPDATE_DATA_SET';
export const CURRENCY_PRICE = 'CURRENCY_PRICE';

export const UPDATE_COIN = 'UPDATE_COIN';
export const UPDATE_REDDIT_THREAD = 'UPDATE_REDDIT_THREAD';
export const UPDATE_PRICE_CHANGE = 'UPDATE_PRICE_CHANGE';
export const UPDATE_MARKET_CAP = 'UPDATE_MARKET_CAP';

export const RECEIVE_GRAPH_DETAIL_SET = 'RECEIVE_GRAPH_DETAIL_SET';

export const RECEIVE_TIME_SELECTION = 'RECEIVE_TIME_SELECTION';
export const RECEIVE_HIGH_LOW = 'RECEIVE_HIGH_LOW';
export const RECEIVE_VOLUME = 'RECEIVE_VOLUME';
export const RECEIVE_WEIGHTED_AVERAGE = 'RECEIVE_WEIGHTED_AVERAGE';

export const CLEAR_GRAPH_DATA = 'CLEAR_GRAPH_DATA';
export const CLEAR_GRAPH_PREVIEW_DATA = 'CLEAR_GRAPH_PREVIEW_DATA';