# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'setcrypt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    pod 'SwiftyJSON', '3.1.4'
    pod 'Charts', '3.0.1'

  # Pods for setcrypt

  target 'setcrypt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'setcryptTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

